### PR TITLE
Implement Config Info annotation

### PR DESCRIPTION
**Pull request by andreaTP**

### CODE REVIEW

**Review by EricWittmann — APPROVED** [review]

**Comment by EricWittmann** [comment]
Let me know if you want a new release of this repo.

**Comment by andreaTP** [comment]
Maybe let's wait for @jsenko feedback, if all the fields are appropriately encoded we can release 🙂

**Comment by andreaTP** [comment]
Reading @jsenko comment on the related PR in `registry` this is good to go, would you mind triggering a release @EricWittmann ?

**Comment by andreaTP** [comment]
Thanks!

**Pull request merged**
